# Generated by Django 5.0.2 on 2024-04-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='documento',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_documento',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
