# Generated by Django 5.0.2 on 2024-04-12 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0002_persona_documento_persona_tipo_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='persona',
            name='tipo_documento',
        ),
        migrations.AlterField(
            model_name='persona',
            name='documento',
            field=models.OneToOneField(max_length=10, null=True, on_delete=django.db.models.deletion.PROTECT, to='Persona.documento'),
        ),
    ]
