# Generated by Django 5.0.2 on 2024-04-13 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0003_documento_remove_persona_tipo_documento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='documento',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='documento',
            new_name='tipo_documento',
        ),
    ]
